### ISSUE TITLE
2 octet SvcParamKey may not be extensible enough

### ISSUE THREAD

**Issue by ericorth** [MikeBishop/dns-alt-svc#113]
Inspired by the conversation in issue #112: If we're concerned about the ability to add and experiment with new transports if using SvcParamKey, that may mean SvcParamKey just has a more general issue because I wouldn't expect the transports to require change particularly more often than anything else.

At issue, it seems 1 octet worth of code points for "private use" may not be sufficient for experimentation with new fields (or new transports if we make transports into top-level fields).  Too much chance of conflict with other uncontrolled usage of the private use block.  Seems we wouldn't really be able to use the block at all for experimental new stuff unless we constantly grease with random values from that range and the spec encourages wonky practices like always checking for a checksum in the value to ensure it's actually the param type the client is looking for.  And 2 octets is probably not enough availability overall to let anybody claim large chunks in the registered blocks for multiple experimental code points.

I suggest we increase to 4 octets, make the unregistered block much larger to reduce the chances of conflicts, and encourage temporary registration of experimental parameters.  Feels to me that 4 octets would be worth it for the main extensibility mechanism of SVCB.  We'd also be able to save a bit of those octets back when params like the EsniConfig could more reasonably create new parameters for new versions instead of spending octets to do versioning within the parameter value as is the current plan.

**Comment by bemasc** [comment]
One funny thing about going to 4-byte IDs is that it makes a straight encoding markedly less efficient than CBOR.

I think we should try hard to avoid having separate ESNIConfig SvcParamKeys for different versions, because it would greatly complicate the interface between TLS and DNS (e.g. between OpenSSL and BIND).

**Comment by enygren** [comment]
We should leave it at 2 octets and not go crazy.  We can always do an extended SvcParamKey type some year if this ever becomes an issue.

Using different SvcParamKeys for different versions is also going to slow roll-out due to the need to get those into more vendors (eg, DNS providers).

**Comment by bemasc** [comment]
Closing in favor of #154
