### ISSUE TITLE
Consider switching back to ALPN

### ISSUE THREAD

**Issue by enygren** [MikeBishop/dns-alt-svc#115]
Based on some feedback from @martinthomson we should consider switching back to ALPN rather than introducing "transport".  As part of this we'd want to clarify that:
1) ALPN defines the whole stack  (eg, "H2-over-TLS-over-TCP" )
2) The alpn thus implicitly specifies a transport protocol but also allows filtering of higher-level protocols (ie, to allow doh and dot on different endpoints).
3) Secure in-band negotiation takes precedence, so if the alpn negotiated is different from one indicated in the record then the client MUST use it.

We'd then switch from having a default transport protocol to a default alpn (eg, "http/1.1" for HTTPSSVC) and have no-default-alpn as a param.

**Comment by MikeBishop** [comment]
Done in #116.
