### ISSUE TITLE
Clarify how clients select between multiple alpns in a set

### ISSUE THREAD

**Issue by enygren** [MikeBishop/dns-alt-svc#117]
It is ambiguous how a client selects which transport to use if multiple are provided in a set, all of which the client supports.  For example with:
   alpn=h3,h2
or:
   alpn=h2,h3
(with the implicit http/1.1).

Since we don't want to make this a list, the best way to handle this may be to specify that clients should apply their own heuristics for selecting which underlying transport (eg, TLS or QUIC) to try connecting with first as well as whether to try racing to both.

Operators wishing to force an ordering should then use different SVCB records at different priority levels.

**Comment by davidben** [comment]
Ordering isn't necessarily a well-defined notion. Chrome doesn't try QUIC and then TCP. We race the two. (A network which is intolerant to QUIC may simply drop the packet and appear like a QUIC timeout.)

**Comment by enygren** [comment]
Won't fix for now.

**Comment by MikeBishop** [comment]
Client heuristics are sufficient.
