### ISSUE TITLE
Improve description of QNAME structure

### ISSUE THREAD

**Issue by bemasc** [MikeBishop/dns-alt-svc#122]
Currently, the QNAME structure is described as a _port._scheme.domain, except "mappings for SVCB MAY remove the port".  This is potentially confusing.  We should align the terminology with the URI (URL?) RFCs, and discuss ports only in the context of HTTPS.

> section 1.1 
> 
>  _8765._baz.api.example.com. 7200 IN SVCB 0 svc4-baz.example.net.
>  
> 
> In my opinion, the mechanism that derives QNAME needs to be refined or maybe
> the terminology being clarified. 
> 
> a) The current document describes how to generate the QNAME from an URI. The
> QNAME contains a port number while some scheme do not allow or specify port
> subcomponent. Not having the port specified could be particularly useful to
> provide secure transport for schemes that are not necessarily secure for
> example. One the other hand, a scheme that specify a port, may not necessarily
> need to have it specified twined in the QNAME. I would be rather inclined to
> have the port optional maybe at the expense of an additional RRset, but need
> more thoughts.  
>   
> b) It is also unclear to me why HTTPS:443 or HTTP:80 has a specific convention.
> The convention tales place for the DNS resolution of a authority as opposed to
> the DNS resolution of a FQDN. One possible reason I see could would be to
> prevent having a distinction between http and https (which could be done
> otherwise for example using alpn),  but I am wondering if there are other
> rationale. So far, I do not see the need for a exception for the derivation of
> the QNAME (nor for using a specific RRtype).    
> 
> c) The current document, mentions several time HTTP service. The term service
> seems to me ambiguous as it has been defined for the DNS service based
> discovery in which case it means a web page. It seems to me preferable we keep
> the scope of URI scheme and port authority. As a side note, when scheme is
> thought as a service, the convention adopted by the document slightly differs
> from the DNS based service Discovery which would use _baz._udp or eventually
> _baz._tcp. The current approach may be simpler.. I would think this is mostly a
> terminology issue.  
>
> section 2.3 
> 
> """
> Protocol mappings for SVCB MAY remove the port or replace it with
>    other protocol-specific information, but MUST retain the scheme in
>    the QNAME.  
> """
> 
> I understand that for any scheme, a definition of how scheme and port should be
> defined when using SVBC. If that is correct, I would rather see that the other
> way around, that is SVBC defining from the scheme definition the QNAME
> derivation. The term MAY also suggest different interpretation will be
> permitted, which could affect interoperability. 
>

**Comment by enygren** [comment]
Addressed in #157
