### ISSUE TITLE
Clarify non-HTTPS example

### ISSUE THREAD

**Issue by bemasc** [MikeBishop/dns-alt-svc#124]
This example currently fuses two different zone files.  We can make it clearer that they are separate by adding a comment line above each RR.

> """
>  As an example:
> 
>    _8443._foo.api.example.com. 7200 IN SVCB 0 svc4.example.net.
>    svc4..example.net.  7200  IN SVCB 3 ( svc4.example.net. alpn="bar"
>                                       port="8004" esniconfig="..." )
> """
> 
> While many examples are useful for the understanding, they often provide the
> impression RRsets are in the same zone file. I am wondering if that would not
> be clarifying to show and mention zone files are different. Note this is just a
> feed back and your ar efree to ignore it.

**Comment by enygren** [comment]
Merged PR #129
