### ISSUE TITLE
Justify keeping AliasForm and ServiceForm in one RR type, or split them into two

### ISSUE THREAD

**Issue by bemasc** [MikeBishop/dns-alt-svc#125]
We've gotten multiple comments asking why AliasForm and ServiceForm aren't separate RR types.  From a recursive resolver's perspective, this would simplify the processing logic.  However, it would also result in double the QPS for everyone, since clients would have to fire off simultaneous queries for _both_ Qtypes.

> It seems strange to me to have a single RRset type associated to different
> functionalities, i.e. Alias and Service. I suspect that it is more convenient
> to have the same RRtype while requesting among different administrative
> domains, but I would be happy to know the rationals for this design. I have the
> impression that alias form is used to indicates the next RRtype (in our case,
> SVCB) while service form indicates a terminal request.

**Comment by enygren** [comment]
We should make sure this rationale described in the appendix and then close this as WONTFIX.

**Comment by bemasc** [comment]
Actually, I think it's worse than double.  A client, not knowing whether its recursive will perform special-case handling of these queries, has to issue both queries immediately.  A recursive, upon seeing a ServiceForm query, would itself have to issue both ServiceForm and AliasForm queries, both at this point in the chain and subsequently at every point down the chain.  So it somewhat more than doubles the load of the whole design, and the recursive behavior is possibly even more complex.

**Comment by enygren** [comment]
Added a justification in PR #128
