### ISSUE TITLE
Unrecognized keys in presentation format

### ISSUE THREAD

**Issue by DesWurstes** [MikeBishop/dns-alt-svc#130]
> Unrecognized keys are represented in presentation format as
   "keyNNNNN" where NNNNN is the numeric value of the key type without
   leading zeros.  In presentation format, values of unrecognized keys
   SHALL be represented in wire format, using decimal escape codes (e.g.
   \255) when necessary.

Isn't this self-contradictory?

**Comment by bemasc** [comment]
The intent is that, if you encountered (e.g.) the "alpn" key but didn't have support for it, you would present it as

    key1=\008http/1.1

The text is attempting to distinguish between "unrecognized keys" and "value of unrecognized keys".  If that's not clear, we can change the text -- suggestions welcome.

**Comment by DesWurstes** [comment]
Thanks, it's clear now. From `values` I understood the numerical values of keys while it meant corresponding values.
