### ISSUE TITLE
Request: combine ABNF in one place

### ISSUE THREAD

**Issue by moonshiner** [MikeBishop/dns-alt-svc#138]
This is more of a "nice to have" but would it be possible to have an appendix with all the ABNF in one place, along with the references to other documents where other definitions exist? 

Be glad to send a pull request.

**Comment by bemasc** [comment]
Sure, PRs welcome!

**Comment by moonshiner** [comment]
https://github.com/MikeBishop/dns-alt-svc/pull/139  is to fix up minor validation issues.
