### ISSUE TITLE
Consider a way to indicate some keys as "mandatory"

### ISSUE THREAD

**Issue by bemasc** [MikeBishop/dns-alt-svc#166]
@enygren has proposed identifying a key range as "mandatory".  A client encountering an unrecognized "mandatory" key would discard the entire RR.

The current draft already relies on mandatory understanding for the "port" and "alpn" keys.  Without a mandatory range, keys of this kind could not be defined in a future draft.

PR #164 is an example of something that might make sense as a followup RFC, but currently can't be because of the lack of such a range.

Previously, this seemed somewhat artificial to me, but with the new partitioned key ranges it doesn't seem so strange.  Perhaps we could assign this meaning to the new 1-255 "Standards Action" range.

EDIT: Alternatively, this could be its own SvcParamKey, e.g. `mandatory=port,alpn`.
EDIT2: Using 1-255 seems like a very small range, but if we ever get close to running out, we can simply define a `mandatory` SvcParamKey in that range, and use it to extend the behavior indefinitely.  So if we choose a range, it can be small.

**Comment by MikeBishop** [comment]
We wouldn't want that meaning for all Standards Action values, though; certainly someone might define an optional-to-understand value in a standard.  Given than new values in each range might want to define either type of value, I'd be more inclined toward a `mandatory=` parameter which lists the parameters which must be understood to consider this entry.

**Comment by tfpauly** [comment]
I agree with @MikeBishop that we shouldn't necessarily tie the Standards Action range to being mandatory. I can see reasons to have mandatory keys that are in non-standard ranges, and reasons to have standardized values that aren't mandatory.

Beyond that, I can see it being reasonable for the existing keys (ech) to be not supported by a client at first, while ALPN is, etc.

I'd prefer to see a `mandatory=` parameter as well to allow the record to specify more clearly which parts it finds necessary. Right now, the value `0` is `Reserved for internal use`. Could this be used perhaps as the `mandatory` key? The value would be a list of other keys, and this would also have the nice benefit of being required to be first key in the list, so clients know up front if they support all the mandatory fields.

**Comment by enygren** [comment]
I also like this idea of mandatory= parameter using SvcParamKey=0.

(Would we want to also allow mandatory= to appear on Alias form but without any defined/allowed parameters.  That creates a future for parameters on Alias form but without needing to define any now?)

**Comment by bemasc** [comment]
I'm OK with 0 -> `mandatory`, but I also like 1 -> `mandatory`, leaving 0 for use as some kind of null.

I have some concerns about allowing it in AliasForm.  That would have several knock-on effects:
* Recursive resolvers would have to parse the SvcFieldValue, to see if it contains an unrecognized mandatory key.
* Multiple aliases in an RRSet would have to be allowed, to support recursive and clients that can't use one of the aliases due to a unsupported mandatory key.  This would then require some kind of preference ordering among multiple aliases, assuming that the new mandatory key is actually useful.

This proposal is already pretty complicated, and we don't have a use case for mandatory keys on aliases, so I think we're probably better off keeping `mandatory` ServiceForm-only, like the other keys.

**Comment by bemasc** [comment]
One problem with "mandatory" is how to deal with `alpn` and `port`.  These are both already mandatory: you can't connect if they are present and you don't understand and use them.  Some options:
* Require every record that uses `port` or `alpn` to have a `mandatory` key.
* Special-case these two keys as implicitly mandatory
* Assign a range of mandatory keys (i.e. encode it as a flag in the key id)
* Make keys mandatory by default, and define an `optional` key.

I'm beginning to feel like the last option is the least error-prone and most comprehensible.  It would have some interesting side effects, such as allowing endpoints that not only support ECH but actually require it.

**Comment by enygren** [comment]
I think optional is a saner default.  As such, I'd lean towards either allowing protocol bindings to specify a set of implicitly mandatory keys  (HTTPS would specify alpn and port.), or just special-casing those two in general.

**Comment by tfpauly** [comment]
Optional is definitely the better default. Don't make keys mandatory in general.

I'd say we can have those two keys implicitly mandatory if we really want (option 2)—or just leave it to the deployment to mark what *they* think is mandatory (option 1). Yes, your use case for `port` is mandatory now, but that doesn't there couldn't be possible use cases in which you can have an alpn value that for some reason an implementation doesn't parse, but also have fields in the record that mean it shouldn't be thrown out.

**Comment by moonshiner** [comment]
Agree with "don't make keys mandatory in general" logic.

**Comment by bemasc** [comment]
OK, I've written up a PR for "mandatory", #205, reflecting the input here.

One difference: I didn't reorder the list of IANA codepoints.  I'm happy to do that if people have feelings about which number should mean what.
