### ISSUE TITLE
Whether to include weight as a parameter

### ISSUE THREAD

**Issue by enygren** [MikeBishop/dns-alt-svc#167]
Moving this issue out of the text (even if we WONTFIX it for now):

## Whether to include Weight

Some other similar mechanisms such as SRV have a weight in addition
to priority.  That is excluded here for simplicity.  It could always be
added as an optional SVCB parameter.

**Comment by moonshiner** [comment]
I argue for "no".  You are going down the slippery slope of SRV. 

The only places I've seen usage of SRV is  by - SIP, Kerberos,  and XMPP
