### ISSUE TITLE
SVCB record include service name in RDATA?

### ISSUE THREAD

**Issue by enygren** [MikeBishop/dns-alt-svc#168]
Moving from the draft to an issue.
Proposing to WONTFIX this.

Another open question is whether SVCB records
should be self-descriptive and include the service name
(eg, "https") in the RDATA section to avoid ambiguity.
Perhaps this could be included as an svc="baz" parameter
for protocols that are not the default for the RR type?
Current inclination is to not do so.

**Comment by moonshiner** [comment]
Agree here
