### ISSUE TITLE
"NOT REQUIRED" not a legit 2119 keyword

### ISSUE THREAD

**Issue by moonshiner** [MikeBishop/dns-alt-svc#171]
In the section "Using SVCB with HTTPS and HTTP" the text says "NOT REQUIRED" and while I agree the upper case adds the gravitas, it's not a legit 2119 keyword.

**Comment by MikeBishop** [comment]
Hm, I think that technically we want a "MAY not implement Alt-Svc," but the naive reading of that is that you're not allowed to implement.

**Comment by moonshiner** [comment]
My opinion is we don't need the 2119 language.  I was offering the option if the authors feel they want one.

**Comment by moonshiner** [comment]
This can. be closed
