### ISSUE TITLE
Definition of "origin server"

### ISSUE THREAD

**Issue by martinthomson** [MikeBishop/dns-alt-svc#183]
> The "origin server" is the server that the client would reach when accessing the origin in the absence of the SVCB record or an HTTPS Alt-Svc.

HTTP has a definition of origin server that this is not compatible with.  In HTTP an "origin server" is a server that is authoritative.  As the goal of this document is to define alternative ways to reach a server that is authoritative, the definition this document uses is very confusing.

I don't have a solid alternative at this point, but I might suggest that the notion of "whatever you get when this record isn't used" isn't a very useful distinction.  As a hypothetical, consider a protocol that only uses SVCB derivatives for discovery, which would obviously have no such concept.  It might be better to dispense with the notion of "original server" entirely.

**Comment by martinthomson** [comment]
One example of where this term is used:

> The "port" SvcParamKey defines the TCP or UDP port that should be used to contact this alternative service.  If this key is not present, clients SHALL use the origin server's port number.

**Comment by tfpauly** [comment]
The only other place this is used is:
```
If none of the options succeed, the
       client SHOULD connect to the origin server directly.
```

It seems like this term is used sparsely enough it can be dispensed with, and the sentences reworded.
