### ISSUE TITLE
ABNF for values

### ISSUE THREAD

**Issue by martinthomson** [MikeBishop/dns-alt-svc#185]
The definition of values allows for quoting, but the ABNF doesn't capture that.

```
   escaped-char  = "\" (VCHAR / WSP)
```

This implies that "\3" is valid, where it is not.  Capturing this is not so difficult.

```
   basic-visible = %x21 / %x23-27 / %x2A-3A / %x3C-5B / %x5D-7E
   unescaped = %x21 / %x23-27 / %x2A-2F / %x3C-5B / %x5D-7E
   escaped-number = (%x30-31 2DIGIT) / (%x32 (%x30-34 DIGIT) / (%x35 %x30-35))
   escaped-char  = "\" (unescaped / WSP / escaped-number)
```

**Comment by moonshiner** [comment]
should "%2A-3A" be " %x2A-3A" ?
same for " %2A-2F " ?

**Comment by martinthomson** [comment]
Edited to add the 'x'.  As I copied this, I hope that this wasn't something I copied in.

**Comment by moonshiner** [comment]
I put a copy of the (updated) extracted ABNF in https://gist.github.com/moonshiner/3aa994227226c9e5b33dc808a8937574

This does run through 'bap' w/out errors.

**Comment by moonshiner** [comment]
https://github.com/MikeBishop/dns-alt-svc/pull/160 updates the ABNF slightly.

Also, we have "key" and "display-key" but currently only use "display-key"

**Comment by bemasc** [comment]
For this issue, the relevant PR is #202.  PR #160 also makes some colliding changes, but it's not directly relevant to this issue.  If one of those PRs is approved, I'll merge it and resolve the collisions in the other PRs.
