### ISSUE TITLE
Use colons before examples

### ISSUE THREAD

**Issue by martinthomson** [MikeBishop/dns-alt-svc#186]
Such as in:

```
   As an example, the owner of example.com could publish this record

   _8443._foo.api.example.com. 7200 IN SVCB 0 svc4.example.net.
```

Text forms don't have clear delineation of example and text and without a colon it is harder to read.

**Comment by moonshiner** [comment]
https://github.com/MikeBishop/dns-alt-svc/pull/198

Should catch all those missing colons.  A double check before merging would be apprecriated
