### ISSUE TITLE
Aliases to A/AAAA records

### ISSUE THREAD

**Issue by martinthomson** [MikeBishop/dns-alt-svc#188]
It's not clear why this is useful as opposed to having a ServiceForm SVCB at the target of an alias.  Some words on the subject would be greatly appreciated.

**Comment by davidben** [comment]
It also, as I understand things, means a client which sees a chain of HTTPS alias forms must, at each stage in the process, issue new parallel A/AAAA/HTTPS queries since we can't assume that the three will get stapled together.

**Comment by enygren** [comment]
Is the wording following #209 good enough for us to close this?
