### ISSUE TITLE
Presentation of ALPN

### ISSUE THREAD

**Issue by martinthomson** [MikeBishop/dns-alt-svc#192]
The presentation format for ALPN is not consistent with the generic presentation format.  It also includes unprintable characters.

**Comment by marka63** [comment]
Apart from having to recognise "\," vs "," and having to remember which commas where escaped and which where not, APLN are still a optionally quoted string.  e.g. ALPN="x\,y,z" or ALPN=x\,y,z

**Comment by martinthomson** [comment]
It is unnecessarily different.  And it's not clear that the same escaping rules apply.  In the presentation format I might include \000 to include a literal NUL, but it appears to require the inclusion of a literal NUL preceded by a backslash in the ALPN format.

If the section said "just like the presentation format, but you have to escape comma" then it might be understandable, but the differences are inexplicable.

**Comment by enygren** [comment]
Larry Campbell (@lcampbel) also found this unclear, so it does seem like we should clarify.

**Comment by moonshiner** [comment]
How about a couple of examples?

**Comment by enygren** [comment]
Fixed in #202.  Good enough now?
