### ISSUE TITLE
Advice regarding construction of ALPN extension in TLS

### ISSUE THREAD

**Issue by martinthomson** [MikeBishop/dns-alt-svc#194]
>    Clients MUST include an "application_layer_protocol_negotiation" extension in their ClientHello with a ProtocolNameList that includes at least one ID from the ALPN set.  Clients SHOULD also include any other values that they support and could negotiate on that connection with equivalent or better security properties.  For example, if the ALPN set only contains "http/1.1", the client could include "http/1.1" and "h2" in the ProtocolNameList.

This could be read to imply that a client conditions its choice of ALPN parameter in a TLS ClientHello based on what it learns from SVCB.  This is dangerous as it exposes the connection to potential downgrade attacks.  Though it tries to recommend that "better" options be chosen, this is a determination that the server makes in ALPN, not the client.  This document should instead mandate that clients construct an ALPN extension containing all protocols that they are willing to use.

**Comment by MikeBishop** [comment]
I think that depends on how you define "downgrade."  The existing text says that the client includes:
- At least one ALPN token from the SVCB record(s)
- Any protocol the client supports which it considers "better" than the least-preferable selected token, even if not in the SVCB record

But the point that it leads to selection involving the client's definition of "better" versus the server's is certainly a fair point.

**Comment by davidben** [comment]
Wait, I remember this "better" formulation already came up and was rejected, for precisely this reason. The network does not get to influence the selected ALPN protocol. This notion of "better" breaks any formal notion of downgrade protection. It also has practical consequences beyond downgrades: even if client and server agree that h2 is better than http/1.1, the current draft text makes h2 SVCB break if, say, the server needed to rollback h2.

I agree with Martin that this text needs to change change. Both http/1.1 and h2 SVCB records must result in the *exact* same ALPN advertisement, namely all the client's accepted protocols. The only acceptable filtering is that inherent to collections of compatible ALPNs. Beyond that, SVCB stays out of the TLS ALPN negotation.

**Comment by enygren** [comment]
Merged in #201.  Good enough to close?
