### ISSUE TITLE
Unclear precedence rules

### ISSUE THREAD

**Issue by martinthomson** [MikeBishop/dns-alt-svc#196]
At one level, the precedence rules for this specification could be simple: take the RRs with the lowest priority and select at random between them.  This is clearly the case for the 0/other split.

But it isn't that simple, because RRs with lower priority might not have options that the client supports.  So some configurations are eliminated.

Moreover, there are cases where server/operator preference and client preference might be in tension.  Let's say that the client greatly prefers HTTP/3 over HTTP/1.1.  Is it required to use an HTTPS RR with HTTP/1.1 and a lower priority if a higher priority supports HTTP/3?

More difficult, what if the higher priority has echconfig and the lower priority one does not?  Section 8.1 might be read to imply that echconfig overrides other considerations, but it isn't very clear on that point.  Also, we have to consider an echconfig that the client does not support specially, as that does not imply that the RR lacks echconfig.

**Comment by bemasc** [comment]
Change #204 includes some changes that might make this clearer.  However, I think precedence rules are pretty clear: clients shuffle, sort, and walk down the list.  If they run out, they fall back to normal connection.  (Special case: if all attempts had ECH, and all failed, don't fall back to non-ECH.)

The order of attempts is SHOULD and MAY, so sufficiently smart/opinionated clients can mess with it if they want.

**Comment by enygren** [comment]
Is this good enough now that #204 has been merged?
