### ISSUE TITLE
Limit key name length

### ISSUE THREAD

**Issue by bemasc** [MikeBishop/dns-alt-svc#213]
Presentation format key names are not currently explicitly limited (although the IANA experts would surely reject an absurdly long name).  @marka63 has requested a name length limit.

Plausible values include 255, 64, and 63.

**Comment by enygren** [comment]
Why not 63 (consistent with DNS label length limit)?  Can we put the limit in the IANA section?

**Comment by bemasc** [comment]
I would want to update the ABNF so parsers can rely on the length limit.

**Comment by bemasc** [comment]
I added a limit of 63 to #202.

**Comment by enygren** [comment]
Fixed in #202
