### ISSUE TITLE
Do we allow "mandatory" to appear in the "mandatory list"?

### ISSUE THREAD

**Issue by marka63** [MikeBishop/dns-alt-svc#225]
My feeling is no as it simplifies processing of the record as you don't have to check for it just to skip it.   Also it is implicitly there just by the presence of the field.

**Comment by bemasc** [comment]
Agreed.  I believe this is already covered in the text:
> This SvcParamKey is always automatically mandatory, and MUST NOT appear in its own value list.

**Comment by marka63** [comment]
It's there with the "also" in "MUST also appear" but that is very subtle.  I suggest adding "(This implies "mandatory" MUST NOT be a element of the list)" or similar.
