### ISSUE TITLE
Add the expanded form of "SVCB" when it's first used

### ISSUE THREAD

**Issue by cbartle891** [MikeBishop/dns-alt-svc#229]
Typically, when introducing an acronym, it's useful to include its expanded form with it. That doesn't seem to happen in this document for "SVCB," nor does SVCB appear to be a common DNS term like RR. In fact, SVCB doesn't appear to be an acronym at all, but rather a shortened version of "Service binding." Is this true? If so, indicating that would be helpful.

**Comment by tfpauly** [comment]
Isn't this covered in Section 1.4?

```
SVCB is a contraction of "service binding".  The SVCB RR, HTTPS RR,
   and future RR types that share SVCB's format and registry are
   collectively known as SVCB-compatible RR types.
```

**Comment by cbartle891** [comment]
Ah, that's good, but that's why I specified "when introducing an acronym." It's very delayed to explain an acronym (or abbreviation) 6 pages after it's first used. I've changed the title of this issue accordingly.
