### ISSUE TITLE
Confirm IANA actions for  Service Parameters Registry

### ISSUE THREAD

**Issue by moonshiner** [MikeBishop/dns-alt-svc#232]
In discussing draft-schwartz-svcb-dns Draft, @bemasc and I were debating the need for "Standards Action" vs "Expert Review"

I suggest changing it to "Expert Review / Specification Required"

**Comment by bemasc** [comment]
@moonshiner I'm not sure I understand your proposal.  Currently we have 256 Standards Action, 32512 Expert Review, 32512 FCFS, and 255 Private Use.  What are you suggesting?

**Comment by moonshiner** [comment]
In talking with Ben, and some discussions during the working group, I was realizing that "Standards Action" is a higher bar than "RFC Required".  I just wanted to make sure that was good.  But "Expert Review" actually should be enough for the second group,and I'm good with that.   Closing.
