### ISSUE TITLE
Interpretations of Generic Parameters (Unrecognized Keys)

### ISSUE THREAD

**Issue by rthalley** [MikeBishop/dns-alt-svc#235]
Hi there!  I'm one of the maintainers of dnspython and have started implementing SVCB.  I'd like to verify a few aspects of my interpretation of generic parameters.

Here are things I think are true from reading the spec (draft-ietf-dnsop-svcb-https-01), do the authors agree?

1) The parameter

   key1="\002h2"

is the same as

   alpn="h2"

The clarification I'm looking for is that the wire format value is the format of JUST the value of the parameter, and does NOT include the 2-byte length-of-the-whole-value prefix from the wire encoding as well.  (This makes sense to me as the length would be redundant, but just checking!)

2) The parameter

   key2

(i.e. the generic form of no-default-alpn) by itself is illegal, because a generic thing is always a "single-valued" param whose value is the wire format.  There is no value here, so it's an error.   (Section 2.1)

3) The parameter

   key2=

is illegal because the EBNF doesn't allow "=" without something following it.  (Section 2.1)

4) The parameter

   key2=""

is the legal way of doing no-default-alpn generically, as it specifies an empty wire format.  (This assumes I'm right about item 1) above.)

**Comment by bemasc** [comment]
1. Correct!
2. I disagree.  From the draft ("When the "=" is omitted, the "value" or value list is interpreted as empty."), I would say that `keyN` and `keyN=""` are always equivalent.
3. I agree.

**Comment by bwelling** [comment]
The answer to (2) leads to a followup question - which of `keyN` and `keyN=""` is the preferred form?  (the spec doesn’t really mention canonical text form at all)

**Comment by bemasc** [comment]
I'm not aware of a concept of a "canonical form" for DNS zone files.  For a known key, I would probably follow the heuristic you mentioned, using "" if the key supports nonempty values, and omitting "=" if the key is purely a flag.  For an unknown key ... up to you.

**Comment by bwelling** [comment]
The DNS specifications don't require that all implementations generate the identical text form for all records, but most records are not nearly as complicated as SVCB/HTTPS, and it would be convenient for implementors if the spec provided as much guidance as possible.  The partial examples in the spec are inconsistent about quoting.

**Comment by bemasc** [comment]
Yes, they're deliberately inconsistent to remind the reader that quoting is allowed and optional.

One concern about providing too much guidance on formatting is that implementations might become intolerant of inputs that don't match the "suggested" form, especially if all the serializers produce similar output.

Personally, I view this as a question of aesthetics, and I'm happy to let each implementor make their own choices.
