### ISSUE TITLE
HTTPSSVC: Move "pri" out of the SvcFieldValue

### ISSUE THREAD

**Issue by bemasc** [MikeBishop/dns-alt-svc#24]
It seems like it would be useful for DNS clients to be able to process the priority field directly, without having to gain Alt-Svc parsing capability.  Conversely, "pri" is not needed in Alt-Svc, where values are considered to be ordered already.  Therefore, we should consider a fourth value (`SvcFieldPriority`?) in the RR, present only when `SvcRecordType` is 1.

**Comment by MikeBishop** [comment]
That seems like a reasonable way to adapt this to DNS.

**Comment by enygren** [comment]
Makes sense.  Merged PR.
