### ISSUE TITLE
Clarify presentation format for unrecognized keys

### ISSUE THREAD

**Issue by squarooticus** [MikeBishop/dns-alt-svc#247]
§ 2.1 says:

```
Unrecognized keys are represented in presentation format as
"keyNNNNN" where NNNNN is the numeric value of the key type without
leading zeros. SvcParams in this form are always treated as single-
valued, and the decoded "value" SHALL be used as its wire format
encoding.
```

Does this mean an unvalued key (empty value) would be presented as `keyNNNNN=`?

**Comment by bemasc** [comment]
It would be `keyNNNNN` or `keyNNNNN=""`.

**Comment by squarooticus** [comment]
It might be worth explicitly stating that single-valued with an empty value is equivalent to unvalued.

**Comment by bemasc** [comment]
The previous sentence says `When the "=" is omitted, the `value` or value list is interpreted as empty.`.

**Comment by squarooticus** [comment]
The potential for confusion I'm pointing out is that between a zero-length string and no value. (E.g., in Python, the difference between `''` and `None`.) In this case there is no distinction. The reason this might be confusing to some is that there are three types described (empty, single-valued, and multi-valued), but only two in reality: a single string, and an encoded list of strings. That single string might be zero-length, which can be abbreviated by omitting the `=""`.

I also note there is an added constraint in A.1 that the list of strings in the multi-valued case may not include a zero-length string, which is not clearly simpler to me than simply allowing it, because it then requires special-casing in code that e.g. might want to represent a tuple this way and leave some values blank.

**Comment by bemasc** [comment]
> I also note there is an added constraint in A.1 that the list of strings in the multi-valued case may not include a zero-length string, which is not clearly simpler to me than simply allowing it

This limitation is necessary in order for empty lists to be representable.  Otherwise `list-of-things=""` is ambiguous: is it a single-element list containing the empty string, or a list of length zero?  Applying this limitation seemed easier than requiring all servers to implement a more complex syntax.

None of this actually restricts the syntax of any future key, which can declare itself "single-valued" and then specify any parsing logic that it wants.

**Comment by bemasc** [comment]
Conclusion: Split the multi-value presentation syntax into a separate section (advisory-only), then refer to it normatively from the key definitions that require it.
