### ISSUE TITLE
Upgrade breakage

### ISSUE THREAD

**Issue by squarooticus** [MikeBishop/dns-alt-svc#249]
The behavior normatively specified in § 2.2 for malformed RRs can lead to upgraded clients failing to follow a SVCB chain accepted by an older client. It says:

```
Clients MUST consider an RR malformed if:
...
* the SvcParamValue for an SvcParamKey does not have the expected
format.

Note that the second condition implies that there are no duplicate
SvcParamKeys.

If any RRs are malformed, the client MUST reject the entire RRSet and
fall back to non-SVCB connection establishment.
```

A server that incorrectly specifies a new SvcParam=SvcParamValue will cause clients that can parse said SvcParam to fail, while older clients will ignore it and continue to follow the SVCB chain. Has the alternative of ignoring malformed SvcParamValues been considered? I am actually not sure which behavior produces better outcomes.

**Comment by marka63** [comment]
If a RRset has a broken RR then rejecting the RRset will result in complaints be generated that should make there way back to the operator.   If you just ignore it will never be fixed everybody will have to deploy workaround for the broken record.   All the tools that look at the records then need to handle the broken record in some way.  You need to have different parser behaviour on primary and secondary DNS servers.  Just don't go there.

**Comment by davidben** [comment]
+1 to the existing behavior. It's true that the transition for new features can be messy in general (if my server's HTTP/2 code is broken, only new clients break). This isn't great, but the alternative is *so* much worse.

Once most clients have deployed the new thing, the effect will largely go away. While the new thing is very new, the players are mostly early adopters and thus are more likely to be responsive to complaints of mistakes.

**Comment by squarooticus** [comment]
Ok, seems fine.
