### ISSUE TITLE
Attrleaf on HTTPS RRs

### ISSUE THREAD

**Issue by squarooticus** [MikeBishop/dns-alt-svc#253]
It seems cleaner to say that the HTTPS RRTYPE always implies the http scheme, so that a non-standard port requires only one prepended label for the port. E.g., https://www.example.com:8443 would involve resolution of the name `_8443.www.example.com` rather than `_8443._https.www.example.com`.

**Comment by bemasc** [comment]
That would be more compact, but it is not compatible RFC 8552:

> A global underscored node name is the one that is closest
> to the root of the DNS hierarchy

> If a public specification calls for use of an underscored node
> name, the global underscored node name -- the underscored name
> that is closest to the DNS root -- MUST be entered into this
> registry.

**Comment by squarooticus** [comment]
Ah, ok. Details abound. This makes complete sense now.
