### ISSUE TITLE
TargetName presentation format clarity

### ISSUE THREAD

**Issue by chris-wood** [MikeBishop/dns-alt-svc#296]
Is the TargetName supposed to be a FQDN (with trailing dot) in presentation format? The text doesn't seems to [say so](https://tools.ietf.org/html/draft-ietf-dnsop-svcb-https-02#section-2.1) (unless I'm looking at the wrong thing or overlooking something entirely), but the examples seem to suggest it:

```
   example.com.      7200  IN HTTPS 0 svc.example.net.
   svc.example.net.  7200  IN CNAME svc2.example.net.
```

**Comment by bemasc** [comment]
TargetName is supposed to be a "domain name", which is a specific thing in zone files.  In a zone file, a domain name can be fully-qualified, zone-relative, or even use special syntax like `@`.

**Comment by chris-wood** [comment]
Could we clarify that in the text? I can send a PR if it helps. (I realize this may probably be obvious to DNS experts, but I tripped over it.)
