### ISSUE TITLE
"echconfig" is an "ECHConfigs" struct in ECH

### ISSUE THREAD

**Issue by sayrer** [MikeBishop/dns-alt-svc#298]
> The SvcParamKey to enable Encrypted ClientHello (ECH) is "echconfig".

The ECH draft says this is a list of "ECHConfig" structs: "ECHConfigs".

> The client-facing server advertises a sequence of ECH configurations to clients, serialized as follows.
> ECHConfig ECHConfigs<1..2^16-1>;

This pluralization mismatch tripped me up testing ECH draft-09.

**Comment by davidben** [comment]
Oh oops, I guess this slipped through while this was going through some churn on the ECH side. I'd support renaming the SVCB name to match.

**Comment by bemasc** [comment]
This was deliberate.  From the DNS perspective, this key contains a unitary base64 blob.  Also, even the list-valued keys here have singular names (alpn=..., mandatory=..., ipv4hint=...).

**Comment by sayrer** [comment]
The draft does clarify this distinction in Section 9.

Maybe section 6.3 could say
> The SvcParamKey to enable Encrypted ClientHello (ECH) is "echconfig". Its value, an ECHConfigs vector [ECH], is defined in Section 9.  It is applicable to most TLS-based protocols.

A little bit of redundancy, but the naming is confusing, imo.

**Comment by davidben** [comment]
The singular "echonfig" name seems likely to confuse things. Plain "ech" seems reasonable. (Perhaps we should also re-re-re-reconsider the names in ECH. "ECHConfigs" may have been too clever... ECHConfigList?)

**Comment by sayrer** [comment]
Now would be the right time to do either of those changes. It looks like ECH will need to be revised for the newest HPKE draft, and the wire format of the DNS data will change at that time, too. See https://tools.ietf.org/rfcdiff?url1=https://tools.ietf.org/id/draft-ietf-tls-esni-09.txt&url2=https://tlswg.github.io/draft-ietf-tls-esni/draft-ietf-tls-esni.txt

**Comment by davidben** [comment]
Yes, there are a lot of revisions we know we need for ECH. :-P

**Comment by moonshiner** [comment]
from a DNS implementer/operator point of view, I would like to +1 this small bit of redundancy.

**Comment by bemasc** [comment]
The original context for singular/plural is in #127.

I would prefer to change the name in draft-ietf-tls-esni.  In my view, having structs there named for both the plural and the singular is the main source of confusion.  However, changing the name here is certainly still possible, if increasingly annoying.

While we're talking about changing the name and format, I would also like to revisit the redundant length field.  It seems inelegant, but the main question is what's easiest for TLS library APIs.

**Comment by dmcardle** [comment]
100% agree that ECHConfigs ending with an S is a source of confusion.  Attempting to summarize the various options:

| Name of SvcParamKey  | Name for a list of ECHConfig | General sentiment |
| ------------- | ------------- | ----|
| echconfig  | ECHConfigs  | Confusing! |
| echconfigs  | ECHConfigs  | For consistency, it's desirable for the SvcParamKey name to be singular. |
| ech  | ECHConfigs  | Perhaps undesirable because SvcParamKey name does not hint at a type. |
| echconfiglist  | ECHConfigList  | (I'm personally supportive of this one) |

Also agree that the redundant length prefix is inelegant, but I'd rather keep it. It's really a coincidence that the length prefixes are the same size, and ECH does not prescribe a delivery mechanism.

**Comment by bemasc** [comment]
I think my favorite pairing is probably "ech=" and "ECHConfigList"

**Comment by moonshiner** [comment]
If I may have a say, I'd go with ECHConfigList also.   

Wonderful table @dmcardle

**Comment by enygren** [comment]
How in-flux is ECH at this point, and how many implementations are out there?  Should we also rev the codepoint for the param when ECH stablizes, or is there no implementations/usage out there that matter yet?

**Comment by moonshiner** [comment]
I think cloudflare is the primary deployed implementation.  Most others are branches to stable deployed code.

**Comment by bemasc** [comment]
I don't believe Cloudflare has deployed ECH with SVCB, so they're not yet creating pressure on this codepoint.

ECH is internally versioned, so as long as ECH doesn't break its own internal format (simple TLV just like SVCB), it can rev versions without creating a problem.

**Comment by moonshiner** [comment]
Thanks and that is the best answer.  I don't want to start off throwing away a code point,

**Comment by sftcd** [comment]
On 26/02/2021 22:00, Benjamin M. Schwartz wrote:
> I don't believe Cloudflare has deployed ECH with SVCB, 

Depends what you call "deployed" I guess:

$  dig +short -t TYPE65 crypto.cloudflare.com
\# 135 0001000001000302683200040008A29F874FA29F884F000500490047 
FE0900430013636C6F7564666C6172652D65736E692E636F6D0020C4 
57457B9DEEC27C7F17A1E90F283FC89DF3B7BB31BEAAB8E91CDEB490 
A0284000200004000100010000000000060020260647000007000000 
000000A29F874F260647000007000000000000A29F884F

I don't know of anyone other than developers testing
ECH interop who're using that but you might want to
check with CF.

Cheers,
S.

> so they're not
> yet creating pressure on this codepoint.
> 
> ECH is internally versioned, so as long as ECH doesn't break its own
> internal format (simple TLV just like SVCB), it can rev versions
> without creating a problem.
>

**Comment by sayrer** [comment]
The crypto.cloudflare.com server is what lead me to file this issue, and it is sending an obsolete wire format (ECH draft-09) which uses an obsolete HPKE algorithm (draft-irtf-cfrg-hpke-07). I think it's fine to revise all of these things.

**Comment by chris-wood** [comment]
> I don't believe Cloudflare has deployed ECH with SVCB, so they're not yet creating pressure on this codepoint.

As @sftcd points out, this isn't quite true. Our interop endpoint is live and is using SVCB to mint ECHConfigLists. But we can easily move to something new as needed.

**Comment by sayrer** [comment]
This looks done to me.
