### ISSUE TITLE
Decide which reference type you want for Attrleaf

### ISSUE THREAD

**Issue by moonshiner** [MikeBishop/dns-alt-svc#300]
Normative or Informative? there are both here.

Line Numbers included. 

92:({{https}}) by avoiding the need for an Attrleaf label {{?Attrleaf=RFC8552}}
332:follows the Attrleaf naming pattern {{Attrleaf}}, so the scheme MUST be
981:By removing the Attrleaf labels {{?Attrleaf}}
1366:For services other than HTTPS, the SVCB RR and an Attrleaf label {{?Attrleaf}}
1394:Registry {{!Attrleaf}}.  The scheme SHOULD have an entry in the IANA URI Schemes
1540:Per {{?Attrleaf}}, please add the following entry to the DNS Underscore

**Comment by bemasc** [comment]
Fixed by #351
