### ISSUE TITLE
Why is the reserved key (65535) called "invalid"?

### ISSUE THREAD

**Issue by marka63** [MikeBishop/dns-alt-svc#305]
If the reserved key ever gets used having it be called "invalid" will cause interoperability problems because "invalid" doesn't have a well defined parsing method.  When you give a key a name it also requires a format definition to be specified otherwise you will have different parsers producing different results.

I'm presuming if we ever get to the point where we need more named keys that these will end up being encoded, on the wire, inside this key.  If that happens we will need this key be printed out as key65535 whenever there is a unsupported named type inside this key and if they are all known they will be printed out individually.  The name "invalid" will never be used.

**Comment by bemasc** [comment]
I've posted #306 to remove this name.

Personally, I've found the "invalid" name to be somewhat useful when writing test cases, as a reserved name that is syntactically allowed but guaranteed not to collide with any future key.  However, it's true that it could introduce a special case in pretty-printing code, as you describe.  I've tried to split the difference by reserving the name "invalid" but not mapping it to any codepoint.

In case it's unclear, the purpose of the reservation is to allow code like
```C
uint16 get_key_code(const char* key_name) {
    ...
    return -1;  // Unrecognized or invalid key name
}
```

Overloading it for extensibility might be safe, but it seems more confusing than allocating an ordinary codepoint for that purpose.
