### ISSUE TITLE
Test the Test Vectors

### ISSUE THREAD

**Issue by enygren** [MikeBishop/dns-alt-svc#315]
We added test vectors in PR #312 .  Now that those are merged, it would be preferable for at least two implementors to test and confirm the test vectors.

**Comment by wtoorop** [comment]
@enygren The test vectors are part of the [SVCB and HTTPS PR](https://github.com/NLnetLabs/nsd/pull/167) and used to test the implementation. The PR is currently being reviewed (internally). The test package with the test vectors for NSD can be found here:
https://github.com/NLnetLabs/nsd/tree/features/draft-ietf-dnsop-svcb-https/tpkg/svcb.tdir

**Comment by pieterlexis** [comment]
Many of the vectors came from the PowerDNS unit tests, the newest ones have also been added [here](https://github.com/PowerDNS/pdns/pull/10342/files)

**Comment by bemasc** [comment]
Thanks!  It sounds like these are confirmed.
