### ISSUE TITLE
Remove ambiguities/redundancies in encoding

### ISSUE THREAD

**Issue by enygren** [MikeBishop/dns-alt-svc#32]
From Ilari Liusvaara <ilariliusvaara@welho.com> 

- What if SvcDomainName has length different from its length field?
  DNS wire-form names are self-delimiting (DNS message parsing relies
  on this).
- What does it mean for SvcDomainName to be absent in alternative
  service form? I would guess it means "same as RRNAME".
- Why there is length field for SvcFieldValue? Why not let it run to
  the end of record?
- 2 byte length field can encode values up to 65535, not 65536.
  And the length of SvcFieldValue can not be that big, because
  RRDATA and DNS message length limits (both 65535) would be hit.

**Comment by enygren** [comment]
Using the empty label (".") to specify an absent in alternative service form which means "same as RRName" would address both of the first two items.

**Comment by bemasc** [comment]
But what if the root wants to serve QUIC?  OK, that seems unlikely, but technically it does seem like squatting on their name.  I'm not sure what the formalities of that are.  (I wonder if Let's Encrypt would issue a cert for "."...)

Thinking about the text representation, the clearest way I can think of to indicate an omitted uri-host is to write the SvcDomainName as "*".  I'm not sure what that suggests for the RR serialization though.

**Comment by enygren** [comment]
It seems like some special cases for SvcDomainName to cover for SvcRecordType=1:

* How to indicate it should be equivalent to the RRNAME?
* How to indicate it should be equivalent to the hostname?
* What happens if it has the value "."?  SRV and MX have this
  mean "no service available.

**Comment by enygren** [comment]
Released in -02.
