### ISSUE TITLE
Explore constraints that could decrease presentation format parser complexity

### ISSUE THREAD

**Issue by enygren** [MikeBishop/dns-alt-svc#324]
There has feedback that the current specification introduces significant parser complexity
for some DNS authorities.  We should explore SvcParamValue presentation format
simplifications that don't significant usability but would simplify parser corner cases and escaping.
Preferably this would be done by adding limitations so as to not require major changes to existing implementations.

For example, for ALPN can we limit the allowed presentation format characters for the SvcParamValue
and require any alpn values wanting characters outside of that set to use base64 encoding (with some way
to indicate this).

**Comment by ericorth** [comment]
Would it be reasonable to add any such ALPN character restrictions back to the ALPN identification sequence registry itself? Looking through all the current values (https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids), everything seems to currently be a reasonably limited [a-z./-].  Assuming the TLS WG doesn't object, any downside to just formalizing that restriction for all of ALPN?

**Comment by moonshiner** [comment]
I'd be interested in hearing what the TLS folks think of this

**Comment by enygren** [comment]
Worth considering as well is whether supporting URI templates (a likely common use-case for SvcParamValues) would require complex escaping in the presentation format or whether requiring URI-encoding is good enough.

It would be great if we could:
* Get ALPN scope limited at the registry
* Ensure we can handle URI-encoding without complex escaping/encoding
* Use base64 for anything needing binary encoding
* Drop out lots of the complex escaping/encoding rules for SvcParam values and require new SvcParams to not require them escaping or complex encoding in ways that complicate parsing.

**Comment by bemasc** [comment]
@davidben for input on TLS implications if ALPN is not "8-bit clean" in SVCB.  My impression is that this is not appealing from a TLS perspective.

I have reservations about the idea to "use base64 sometimes".  Whether to use base64 would need to be signalled explicitly by another reserved character, resulting in a novel syntax that's substantially more complicated than the current draft.

An alternative would be to replace the draft's backslash-escaped CSV with RFC 4180 CSV.  RFC 4180 escaping is more complicated, and less DNS-like, but it might reduce implementation complexity for zone file authors who are able to reuse an existing implementation.  I believe this should be acceptable within the early allocation, as it does not affect the representation of any existing valid ALPN, but I don't know that it would satisfy critics of the current syntax.

In principle, we could punt on this question until someone actually tries to register an ALPN with a weird character in it, but that seems likely to create a bunch of headaches, especially related to pretty-printing of wire-format data.  I think we probably need to resolve this now, at least for ALPN.

**Comment by bemasc** [comment]
This topic was [discussed](https://mailarchive.ietf.org/arch/msg/tls/JqhlkWX0H1F4Hi4pjMOcn1tkm-I/) on the TLS mailing list.  I think it's clear that there is not consensus to narrow the allowed characters in ALPN IDs.  Narrowing the allowed range at the registry level also seemed controversial.

For now, I think we need to proceed on the assumption that TLS will not reduce the allowed range.  However, I don't think that means every zone file implementation must be obligated to support the use of characters that no registered ALPN actually uses.  I've proposed #325 as a simplification along that line.

**Comment by bemasc** [comment]
I believe this is resolved by #325.
