### ISSUE TITLE
Wrong section referenced in RFC8126

### ISSUE THREAD

**Issue by ericorth** [MikeBishop/dns-alt-svc#330]
Minor citation bug.  Section 14.3.1 (IANA Considerations > New registry for Service Parameters > Procedure):

> Entries in this registry are subject to a First Come First Served registration policy ({{!RFC8126}}, Section 4.6).

Wrong section.  "First Come First Served" is RFC8126, Section 4.4.  The currently-cited 4.6 is actually "Specification Required".

**Comment by bemasc** [comment]
Thanks!
