### ISSUE TITLE
HTTPSSVC: Be more clear on chaining behaviors

### ISSUE THREAD

**Issue by enygren** [MikeBishop/dns-alt-svc#34]
From Ilari Liusvaara <ilariliusvaara@welho.com> 

- Is there any envisioned use for chained HTTPSSVC records, except
  for type 0 record pointing to type 1 record?
- The MUST requirement to have only one type 0 record and then
  SHOULD behave non-deterministically if this is violated is pretty
  odd.

**Comment by bemasc** [comment]
See also #57.

> MUST requirement to have only one type 0 record

I think this has already been reduced to SHOULD.

**Comment by bemasc** [comment]
Moving discussion to #57.
