### ISSUE TITLE
Referer handling on HSTS behavior

### ISSUE THREAD

**Issue by enygren** [MikeBishop/dns-alt-svc#349]
Given the description:

"client SHOULD behave as if it has received an HTTP 307 (Temporary Redirect) status code with this "https" URL in the "Location" field."

Should we provide any clarification on whether a Referer header should be present (listing the "http" Scheme URI) or omitted?  Or should we leave this undefined?

**Comment by bemasc** [comment]
I think redirects [don't affect Referer](https://stackoverflow.com/a/5441932), so maybe we don't have to worry about this?
