### ISSUE TITLE
Make sure we have the right meaning of "." with wildcard owner names

### ISSUE THREAD

**Issue by bemasc** [MikeBishop/dns-alt-svc#356]
When TargetName is ".", and the record's owner name is a wildcard, it's clear what we want this to mean, but I'm not sure the text formally captures it.

**Comment by enygren** [comment]
Does wildcard even exist as a concept at the level of ownername?  I thought it (and some similar constructs) where a convenience for zone files.  But we should still be clear on this if there's confusion.

**Comment by bemasc** [comment]
As always, the terminology is a bit slippery.  For example, RFC 1034 [says](https://datatracker.ietf.org/doc/html/rfc1034#section-4.3.3)

> In the previous algorithm, special treatment was given to RRs with owner
names starting with the label "*".  Such RRs are called wildcards.
Wildcard RRs can be thought of as instructions for synthesizing RRs.
When the appropriate conditions are met, the name server creates RRs
with an owner name equal to the query name and contents taken from the
wildcard RRs.
