### ISSUE TITLE
question on Appendix D, Figure 5

### ISSUE THREAD

**Issue by rafaelvanoni** [MikeBishop/dns-alt-svc#357]
Hi folks, I'm wondering if the following example is missing the quotes in its wire format portion:
```
   example.com.   SVCB   1 foo.example.com. key667="hello\210qoo"

   \# 32 (
   00 01                                              ; priority
   03 66 6f 6f 07 65 78 61 6d 70 6c 65 03 63 6f 6d 00 ; target
   02 9b                                              ; key 667
   00 09                                              ; length 9
   68 65 6c 6c 6f d2 71 6f 6f                         ; value
   )

   \x00\x01                                           # priority
   \x03foo\x07example\x03com\x00                      # target
   \x02\x9b                                           # key 667
   \x00\x09                                           # length 9
   hello\xd2qoo                                       # value

       Figure 5: A generic key and quoted value with a decimal escape
```

Shouldn't the value line be something like
```
`\x22hello\xd2qoo\x22" 
```
So that it matches the quoted text in the presentation format text ?

Thanks

**Comment by marka63** [comment]
> On 12 Dec 2021, at 11:39, Rafael Vanoni ***@***.***> wrote:
> 
> 
> Hi folks, I'm wondering if the following example is missing the quotes in its wire format portion:
> 
>    example.com.   SVCB   1 foo.example.com. key667="hello\210qoo"
> 
>    \# 32 (
>    00 01                                              ; priority
>    03 66 6f 6f 07 65 78 61 6d 70 6c 65 03 63 6f 6d 00 ; target
>    02 9b                                              ; key 667
>    00 09                                              ; length 9
>    68 65 6c 6c 6f d2 71 6f 6f                         ; value
>    )
> 
>    \x00\x01                                           # priority
>    \x03foo\x07example\x03com\x00                      # target
>    \x02\x9b                                           # key 667
>    \x00\x09                                           # length 9
>    hello\xd2qoo                                       # value
> 
>        Figure 5: A generic key and quoted value with a decimal escape
> 
> Shouldn't the value line be something like
> 
> `\x22hello\xd2qoo\x22" 
> 
> ?

No.  For the double quotes to be part of the value it would need to be escaped.
The value is the part inside the double quotes.

> Thanks
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 

-- 
Mark Andrews, ISC
1 Seymour St., Dundas Valley, NSW 2117, Australia
PHONE: +61 2 9871 4742              INTERNET: ***@***.***

**Comment by rafaelvanoni** [comment]
Ok, but how do I know when to present a value with double quotes (and when not to) ?

**Comment by marka63** [comment]
> On 14 Dec 2021, at 10:20, Rafael Vanoni ***@***.***> wrote:
> 
> 
> Ok, but how do I know when to present a value with double quotes (and when not to) ?

You make a decision as a implementor. There isn’t a canonical format.

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 

-- 
Mark Andrews, ISC
1 Seymour St., Dundas Valley, NSW 2117, Australia
PHONE: +61 2 9871 4742              INTERNET: ***@***.***

**Comment by rafaelvanoni** [comment]
Ah gotcha, they're mixed in the examples so I wasn't sure of that. Thanks for the clarification.
