### ISSUE TITLE
Are HTTPS records supposed to be resolved via CNAME

### ISSUE THREAD

**Issue by bt90** [MikeBishop/dns-alt-svc#358]
Given the following setup:

```
*.example.com.   86400      IN  CNAME      example.com.
example.com.     86400      IN  HTTPS      1 . alpn="h3,h2"
```

Should a query for the HTTPS record of e.g `subdomain.example.com` be resolved using the CNAME?

**Comment by bemasc** [comment]
Yes.  The ability to place an HTTPS record on a CNAME target is the main reason for HTTPS records being distinct from SVCB.

The fact that the CNAME response was generated from a wildcard owner name in the zone file is not even generally visible to the stub resolver.
