### ISSUE TITLE
Combining non-default rejection with mandatory unknown parameters

### ISSUE THREAD

**Issue by bemasc** [MikeBishop/dns-alt-svc#360]
Current text

> To ensure consistency of behavior, clients MAY reject the entire SVCB RRSet and fall back to basic connection establishment if all of the RRs indicate "no-default-alpn", even if connection could have succeeded using a non-default alpn.

@ericorth points out that this does not have the intended effect if the only RRs without `no-default-alpn` are incompatible due to an unknown mandatory key.

Proposed solution:
> ... if all of the *compatible* RRs indicate "no-default-alpn",

**Comment by tfpauly** [comment]
That sounds reasonable. Is it clear the “compatible” refers to the client not knowing mandatory keys, vs the RRs being implied to compatible with one another? Just wondering if another wording might be clearer. Like “all of the RRs supported by the client…”.

**Comment by ericorth** [comment]
There's already a similar usage of "compatible" in section 9.5:

> If an HTTPS RR query for this "https" URL returns any AliasMode HTTPS RRs, or any compatible ServiceMode HTTPS RRs (see Section 8),

So I assume it will be clear enough if given a similar pointer to section 8.

And my one concern about this proposed change is that it gives the zone file operators a little less clarity regarding a golden path for how set up their records to maximize client compatibility.  But then again, setting up only the non-no-default-alpn record with obscure mandatory keys that clients might reject seems to be a pretty unlikely scenario, so it's probably not really a concern in practice unless the domain admins are doing things that they know are silly and compatibility-risky anyway.
