### ISSUE TITLE
Add more forward references to the Overview

### ISSUE THREAD

**Issue by bemasc** [MikeBishop/dns-alt-svc#371]
Requested by Francesca Palombini.

**Comment by fpalombini** [comment]
Thank you.
Additionally, and this is nit-picking (and feel free to disregard my comment) but I think I would not have commented on this sentence:

>    This subsection briefly describes the SVCB RR in a non-normative
>    manner.  (As mentioned above, this all applies equally to the HTTPS
>    RR which shares the same encoding, format, and high-level semantics.)

if it didn't include the term "non-normative". I understand that you meant no BCP 14 terms are used, but requirements can also be considered normative even if they don't use BCP 14 terms. So my simple suggestion would be to rephrase to:

>    This subsection briefly describes the SVCB RR.
>  (As mentioned above, this all applies equally to the HTTPS
>    RR which shares the same encoding, format, and high-level semantics.)
