### ISSUE TITLE
Tracking through Alt SVC lifetimes

### ISSUE THREAD

**Issue by snyderp** [MikeBishop/dns-alt-svc#39]
Similar to how HSTS super cookies are used to track users, I think the Alt SVC lifetime instructions could be used to create implicit long term identifiers for users.  

B/c of local DNS caching, its unlikely that popular (e.g. Apple) protections for HSTS cookies could be applied here (since the context of the DNS request would be lost, there'd be no sense of 1p / 3p requests).

I'm not sure how this issue could be addressed given then proposal, but would be happy to think through one.  This is less a problem with the existing markup / header ALT-SVC options, since the browser can control the life time of those.

**Comment by bemasc** [comment]
It sounds like you're concerned about DNS-based tracking that can identify a user whose IP address has changed.  This is a concern, but it's already present with standard A records.  You can see an implementation of this kind of supercookie at http://dnscookie.com/.

The only solution is for the client to tie its DNS cache to its IP address, so that the cache is cleared when the client's IP address changes.  I don't think HTTPSSVC changes that.

**Comment by snyderp** [comment]
@bemasc A difference here between the DNS cookie and the tracking enabled here is that I could perform it w/o needing to operate any DNS records, I just need a website.  If I can find enough domains sending ALT-SVC DNS headers, I can make requests to those domains from page, see where frame request ends up (or use something like [Performance Nav API](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming) or [Resource Timing API](https://www.w3.org/TR/resource-timing-2/), and use that information as a tracking bit. (its also a very handy history leak…)

Given enough examples, and varying TTLs, i should be able to uniquely identify users.

However, i think the history leak issue here is more alarming

**Comment by bemasc** [comment]
> see where frame request ends up

Do you mean the selected server IP address?  I don't understand the proposed attack.  I don't see why the connection destination would be highly variable, and I don't see how the webpage would learn this IP address (which is not exposed to javascript).

**Comment by snyderp** [comment]
The IP address is not learned.  Whether or not the user has visited a domain previously can probably be teased out (If I understand the proposal correctly).

1) Domain sets up DNS ALTSVC instruction with non-zero lifetime
2) Website includes a resource from that domain on its site
3) Website looks at the [nextHopProtocol](https://www.w3.org/TR/resource-timing-2/#dom-performanceresourcetiming-nexthopprotocol) from the Resource Timing API.  If it request goes to the ALTSVC end point immediately, the user very likely has visited that page before.  If the request goes HTTP -> ALTSVC end point, the user def has not visited that page before

**Comment by bemasc** [comment]
Thanks for the explanation.  I wasn't aware of nextHopProtocol.

I think you are describing the status quo with Alt-Svc, regardless of these DNS-related proposals.  Additionally, the Resource Timing API is guarded by CORS headers (opt-in for each destination domain), and the proposed test is "destructive": after the test is complete, all the tested domains are in-cache, and the tracking information is destroyed.

If there is a privacy concern here, I don't think it is specific to the drafts in this repository.

**Comment by snyderp** [comment]
Yep, Alt-SVC in general has this issue, its not specific to DNS for sure.  But:

1) Its also present in the DNS proposal, so seems important do deal with here before further entrenching Alt-SVC w/o a solution :)
2) Alt-SVC in HTTP headers and markup can be (usually) dealt with in browser privacy tools (Brave is deploying protections, but extensions could also hook into this functionality to protect users).  Browser privacy tools wouldn't have the option of protecting browser users if the info is moved to DNS
3) re CORS-opt in: unfortunately, if there is any lesson from web privacy, its that you can't expect websites to be good at protecting / opt-ing into user privacy (in general), it needs to be something the client / user stack mandates; I don't think CORS is a solution here
4) Thats true for the lifetime of the instruction, sure, but leaking browsing history once per DNS record lifetime is bad!

**Comment by bemasc** [comment]
> Browser privacy tools wouldn't have the option of protecting browser users if the info is moved to DNS

HTTPSSVC cannot be handled by the operating system; it has to be handled by the browser.  I don't know how this would interact with current extension APIs in different browsers, but there's nothing preventing a browser from exposing custom behavior controls for HTTPSSVC.

> you can't expect websites to be good at protecting / opt-ing into user privacy

To be clear, origins have to _add_ a special `Timing-Allow-Origin` header to specify which other origins are permitted to measure their timing.  By default, the Resource Timing API is same-origin only.  I think the odds of an origin accidentally enabling cross-origin resource timing seems very low.

**Comment by snyderp** [comment]
@bemasc apologies for this dropping off

Point taken on the above. I take your point that `Resource Timing API` not being the most likely way of leveraging this.  The main concern is just that the standard allows a site owner / DNS record controller to get the browser to store persistent information that pages can access (indirectly), but which is not (mostly?) w/in the realm of attacks privacy folks are considering.

What are your thoughts on where / if it makes sense to make changes to the standard (or privacy considerations style text) to either alert privacy-oriented implementors of the new attack surface and or reduce it? (i dont have compelling ideas at the moment, saddly)

**Comment by bemasc** [comment]
I think your first step should be to lay out a clear and plausible attack, and ideally put up a demo.  Alt-Svc (and HTTPSSVC) are designed with this class of attacks in mind, and designed with the belief that no such attacks are in fact possible.  If you can demonstrate an attack, I expect the IETF will act forcefully to fix the problem.

You're right that we need to be careful with client-side caching, but HTTP has cookies precisely to allow persistent client identification, along with rules about exactly how to ensure that state is managed appropriately.  These documents are both designed to follow those rules, and thereby avoid introducing privacy problems.

**Comment by MikeBishop** [comment]
Alt-Svc provides a couple of different levers here:

- The `persist=` option indicates whether an entry should be flushed on address change.  Obviously, this is intended to indicate whether the alternative is being recommended because of location (this node is closer to you!) or because of capability (all IPs behind this hostname speak HTTP/3), but an attacker trying to track you wouldn't tell you to flush proactively.
- The Alt-Svc cache is supposed to be flushed whenever cookies are cleared.  This implies that any Cookie partitioning strategy (as Brave is doing) should also partition Alt-Svc records.

However, when Cookies are cleared, I don't believe browsers also force a flush of the OS DNS cache.  This is particularly relevant when the cache contains HTTPSSVC records, since such cached records could reintroduce an Alt-Svc entry the user intended to clear.

It almost seems like we want the records to be short-lived, but the Alt-Svc records they contain to live longer.  Or just use short-lifetime HTTPSSVC records, and provide a longer Alt-Svc entry over HTTPS once the connection is made.
