### ISSUE TITLE
Character String ABNF too strict

### ISSUE THREAD

**Issue by partim** [MikeBishop/dns-alt-svc#395]
First, apologies for bringing this up so late in the process, but I only noticed the issue now while I happened to work on a zone parser.

The ABNF specified in appendix A for `char-string` conflicts with the informal definition given in RFC 1035. Specifically, the ABNF requires all special characters, i.e., `"`, `;`, `(`, `)`, and `\`, to be escaped inside a quoted character string. Conversely, RFC 1035 only requires the double quote to be escaped.

This stricter definition actually is a problem in practice: DKIM and DMARC use semicolons as field separators. Both the examples in their RFCs as well as all ocurrences in wild I have seen use quoted character strings and don’t escape the semicolon.

For instance, RFC 7489 contains the following:

```
     _dmarc  IN TXT ( "v=DMARC1; p=none; "
                      "rua=mailto:dmarc-feedback@example.com" )
```

This will violate the ABNF grammar because of the unescaped semicolons in the first quoted character string.

I think this can be fixed by defining a new rule for characters allowed unescaped in quoted character strings and then redefining `quoted` through it. E.g.:

```
; VCHAR minus DQUOTE and "\"
quoted-char = WSP / "!" / %x23-5B / %x5D-7E
quoted      = DQUOTE *( quoted-char / escaped ) DQUOTE
```

This also fixes a somewhat inelegant nested repetition in the draft’s ABNF where `quoted` contains a repetition of `contiguous` which in turn is a repetition in its entirety.

**Comment by bemasc** [comment]
That sounds reasonable.  Could you format this as a PR?

**Comment by marka63** [comment]
> On 25 Jul 2022, at 07:51, Martin Hoffmann ***@***.***> wrote:
> 
> 
> First, apologies for bringing this up so late in the process, but I only noticed the issue now while I happened to work on a zone parser.
> 
> The ABNF specified in appendix A for char-string conflicts with the informal definition given in RFC 1035. Specifically, the ABNF requires all special characters, i.e., ", ;, (, ), and \, to be escaped inside a quoted character string. Conversely, RFC 1035 only requires the double quote to be escaped.

character-string was very poorly defined in RFC 1035.  It also requires the escape to be escaped inside
double quotes.  Raw EOL also ends up being problem as there are different conventions on different systems.  
In practice you just disallow EOL inside double quotes and require it to be entered with \DDD escaping the
same as you do for the non double quote form.  character-string is supposed to be able to encode arbitrary binary blobs up to 255 octets with a leading length octet.

Master files are supposed to transportable between machines and produce the same wire content. They are text files, possible in a different character set on some machines, which then needs to be converted to ASCII before going onto the wire.  This adds constraints on what is portable.

What is enterable verses what is emitted in presentation form can be very different.  BIND for example
presents octets greater than 125 as \DDD so it can ensure that the field will display in a form that does not require terminals to handle anything other that ASCII.  Other tools processing the record can make other decisions if they need to print it.

> This stricter definition actually is a problem in practice: DKIM and DMARC use semicolons as field separators. Both the examples in their RFCs as well as all ocurrences in wild I have seen use quoted character strings and don’t escape the semicolon.
> 
> For instance, RFC 7489 contains the following:
> 
>      _dmarc  IN TXT ( "v=DMARC1; p=none; "
>                       ***@***.***" )
> 
> This will violate the ABNF grammar because of the unescaped semicolons in the first quoted character string.
> 
> I think this can be fixed by defining a new rule for characters allowed unescaped in quoted character strings and then redefining quoted through it. E.g.:
> 
> ; VCHAR minus DQUOTE and "\"
> quoted-char = WSP / "!" / %x23-5B / %x5D-7E
> quoted      = DQUOTE *( quoted-char / escaped ) DQUOTE
> 
> This also fixes a somewhat inelegant nested repetition in the draft’s ABNF where quoted contains a repetition of contiguous which in turn is a repetition in its entirety.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

-- 
Mark Andrews, ISC
1 Seymour St., Dundas Valley, NSW 2117, Australia
PHONE: +61 2 9871 4742              INTERNET: ***@***.***

**Comment by enygren** [comment]
This is closed in https://github.com/MikeBishop/dns-alt-svc/pull/396 and the draft is in the RFC editor queue.
Can we close this issue?

**Comment by partim** [comment]
Looks like I accidentally deleted my fork during a cleanup assuming the PR had either been merged or rejected.

The draft having progressed without this being solved is a bit unfortunate, but nothing that can be done about it now.
