### ISSUE TITLE
HTTPSSVC: Comments from Brian Dickson

### ISSUE THREAD

**Issue by enygren** [MikeBishop/dns-alt-svc#40]
One minor issue is that wherever CNAME is referenced, you probably want to also include a reference to DNAME, including any implied or explicit chaining of CNAMEs (which could be sequences of CNAME and/or DNAME modulo their respective behavior.)

You might also want to explain the motivation for keeping the FQDN separate from the alt-svc parameters (to make it trivial to parse, and thus to do DNS substitutions like CNAME/DNAME). It is there, just not as up-front as it could be.

It might be a little clearer if the list of alt-svc values (h2, h3, etc) that can occur were to be listed in the document. In particular, the association between h3 and QUIC is inferred but not explicitly called out (at least not that I noticed.)

**Comment by enygren** [comment]
These are not yet addressed in the proposed draft-nygren-dnsop-svcb-httpssvc-00.
We should include in the next version.

**Comment by bemasc** [comment]
> It might be a little clearer if the list of alt-svc values (h2, h3, etc) that can occur were to be listed in the document.

The values are in an IANA registry, and I don't think the "alpn" SVCB parameter is intended to be restricted to a subset of those values.  However, it is true that only some of those values make sense in the context of HTTPSSVC, and their meaning is indeed nontrivial.  I don't think we could enumerate them in the text in any permanent way, but I suppose we could explain the present state of affairs more explicitly.
