### ISSUE TITLE
Mandatory AliasMode parameters

### ISSUE THREAD

**Issue by Saklad5** [MikeBishop/dns-alt-svc#409]
The specification leaves the door open to adding parameters to AliasMode records, but leaves it ambiguous as to how this would affect clients without support.

To eliminate the ambiguity, the "mandatory" SvcParamKey should apply to all records, not just ServiceMode records.

**Comment by Saklad5** [comment]
It wouldn't have to be ignored by a recursive resolver.

**Comment by Saklad5** [comment]
> If mandatory AliasMode parameters were allowed, they would be dangerous to use and complex to specify, because AliasMode records are processed by both the recursive resolver and the client application, but these entities may support different subsets of SvcParams.

@bemasc This applies equally to ServiceMode records.

**Comment by bemasc** [comment]
No: recursive resolvers choose which AliasMode record will be used if there are multiple, but they do not make such a choice among ServiceMode records.

**Comment by Saklad5** [comment]
> No: recursive resolvers choose which AliasMode record will be used if there are multiple, but they do not make such a choice among ServiceMode records.

Clients don't rely on recursive resolvers to choose anything at all. It doesn't actually break anything for a resolver to be unhelpful here.
