### ISSUE TITLE
Inconsistent terminology for what a SVCB is

### ISSUE THREAD

**Issue by davidben** [MikeBishop/dns-alt-svc#414]
Throughout this draft, I've struggled a bit terminology. What is the name of the thing that SVCB *actually gives you*?

- The abstract says "alternative endpoints", though that terminology is odd given SVCB-reliant mode.
- Then the introduction says plain "endpoint" (but that's a rather overloaded word), and "service operator endpoint". It finally says a SVCB RR gives you a "service endpoint".
- Goals then goes back to "alternative endpoints".
- Overview has a mix of "service endpoint" and "alternative endpoint".
- Terminology says "alternative endpoint".
- And then the rest of the document is a mix of "alternative endpoint", "service endpoint", and plain "endpoint"...

Should we pick one? I would propose "service endpoint". It's slightly shorter than "alternative endpoint", less overloaded than "endpoint", isn't really an "alternative" with SVCB-reliant mode, and meshes with the name of the record. (SVCB instead of ALTB.)

**Comment by bemasc** [comment]
Given the history of this document, I'm inclined to avoid any changes without clear instructions from the Responsible AD.  Maybe we can adjust this terminology later.  The RFC Style Guide says that the RFC Editor will

      - Fix inconsistencies (e.g., terms that appear in various forms,
        text that appears multiple times, or inconsistent
        capitalization).

so maybe we can discuss, and potentially adjust, this terminology at that stage.

**Comment by moonshiner** [comment]
Agreed.  We can make a note to bring this up with the RFC editor to get their opinion.

**Comment by davidben** [comment]
While it'd be unfortunate to leave the document in its current hard-to-understand state, I'm really mostly interested in understanding what the intended name was in the first place. Can we agree what terminology would have been preferred if we could still fix the document? And then at least that can be an erratum or an informal note in GitHub, whether or not we reflect it in the document. (Or we can, when bringing it up with the RFC editor, have a preference for which terminology to settle on.)

**Comment by bemasc** [comment]
The terminology is `service endpoint == authority endpoint | alternative endpoint`.  That matches how "service", "authority endpoint", and "alternative endpoint" are defined in Section 1.4.  "service operator endpoint" is a "longhand" for "service endpoint", chosen to be self-describing because it precedes the terminology section, and "endpoint" is a shorthand where the type of endpoint is clear from context.

**Comment by enygren** [comment]
That's up to the Responsible ADs and/or RFC Editor.  A related clarification which was rejected was:

https://github.com/MikeBishop/dns-alt-svc/pull/403

**Comment by davidben** [comment]
@bemasc One more terminology question: what do you call the thing you get if you follow AliasForm and them bottom-out at A/AAAA instead of ServiceForm? That is, the endpoint you get by following this text:

> Once SVCB resolution has concluded, whether successful or not, if at least one AliasMode record was processed, SVCB-optional clients SHALL append to the priority list an endpoint consisting of the final value of $QNAME, the authority endpoint's port number, and no SvcParams. (This endpoint will be attempted before falling back to non-SVCB connection modes. This ensures that SVCB-optional clients will make use of an AliasMode record whose TargetName has A and/or AAAA records but no SVCB records.)

https://www.ietf.org/archive/id/draft-ietf-dnsop-svcb-https-12.html#section-3-6

If it is an "alternative endpoint", that means the "alternative" vs "authority" distinction is no longer useful to answer "did I get SvcParams, ALPN information, etc., with it"? We end up needing a word for that concept a lot, and I've been trying to move from our ad-hoc naming to something more spec-adjacent.

But if it's an "authority endpoint", it's a little interesting because the hostname isn't the thing in the authority portion of the URL.

**Comment by davidben** [comment]
Oh, calling it an "alternative endpoint" also breaks this logic, because this endpoint, whatever it is, won't have ECH keys.
https://www.ietf.org/archive/id/draft-sbn-tls-svcb-ech-00.html#section-4.1

**Comment by davidben** [comment]
(CC @ericorth since we've been discussing the terminology a bit.)

**Comment by davidben** [comment]
For the sake of not having so many words that mean almost-but-not-quite the same thing, I would lightly prefer those still be called "alternative endpoints". But I don't have a good answer for how to square that with with the AliasForm records, if we consider that an alternative (in the sense of not the original) endpoint.

(This came about because we ended up with too many ad-hoc terms like "endpoint with metadata" and "protocol endpoint" in our code, and I'd really like to get to some common, and minimally fussy terminology.)

**Comment by ericorth** [comment]
I'm not seeing any good reason to group alias-only endpoints in with the alternative endpoints since everything dealing with that concept, e.g. SVCB-reliant and the ECH restrictions, really only cares about endpoints with service records or not and the alias-only endpoints do not have service records.  Sure, it would be fair to call them "alternatives", so we could make the concept include them just to make the naming nicer, but then the concept loses most of its value since there's much less reason to differentiate endpoints in that way.  We'd just need to come up with a new name to differentiate the service-record-backed endpoints, and I'm guessing David wouldn't be happy if the result of this discussion were coming up with more naming for similar things.

**Comment by bemasc** [comment]
It seems like we've managed to answer the question and the draft is good enough on this point.  Feel free to reopen or send a PR if there's a specific change you'd like to see.
