### ISSUE TITLE
HTTPSSVC: Security considerations: add note that unauthenticated

### ISSUE THREAD

**Issue by enygren** [MikeBishop/dns-alt-svc#42]
We should add a note to Security Considerations indicating that HTTPSSVC is unauthenticated in many cases (ie, unless DNSSEC is present and verified) and thus care should be taken around Alt-Svc parameters that imply trust.

I wonder if we should be explicit to say that Alt-Svc parameters must opt-in to indicate that they can be used in HTTPSSVC?  (As even with "ma" we've had to define constraints.)

**Comment by bemasc** [comment]
I think this is now addressed pretty clearly: "Alt-Svc parameters that cannot be safely received in this model MUST NOT have a corresponding defined SvcParamKey."
