### ISSUE TITLE
HTTPSSVC: make more generic?  and change record name?

### ISSUE THREAD

**Issue by enygren** [MikeBishop/dns-alt-svc#44]
A question from the DNSOP WG discussion is whether to make this record somewhat more generic, inclduing whether to change the record name.  Some options:

0. Leave as-is and clarify that HTTPS is not just about web browsers.

1.  Rename to ALTSVC.  Keep default behavior for https:// and http:// but clarify that _$label use-cases can be used more generically for other protocols.

2. Make even more generic  (SRVBIS?  SRV2?).  Define that format of the SvcFieldValue is specific to the protocol/scheme.  (ie, might be Alt-Svc for HTTPS.)   

3. Define a generic format with SvcFieldValue being specific to protocol/scheme. But then define a set of RRTYPES that are specific instantiations of this generic format.  For example: HTTPSSVC as an instantiation for HTTPS with Alt-Svc in SvcFieldFalue.  SRV2 as something purely generic.  NS2 for handling secure delegations to DoH/DoT authorities with specification of protocols, ESNIKEYS, ports, etc, in some format of SvcFieldValue.

**Comment by enygren** [comment]
In talking with Tommy Pauly he was leaning towards 1 (ALTSVC).
If we also use this for recursive-to-authoritative DNS then it would want a separate RRTYPE (eg, NS2).

**Comment by tfpauly** [comment]
+1 for option 1.

I'm definitely also eager to get an RRTYPE (like NS2) to point to the authoritative DoH server, in a way that clients can use to discover available trusted DoH servers for given domains. I would also want to the ability for the content to carry a set of keys that can be used with the DoH server (for both ESNI and allowing further encryption of inner queries for obfuscation).

**Comment by bemasc** [comment]
Here's a cut at something like option 3, or maybe even more generic:

An _Indirection RRTYPE_ is an RRTYPE whose contents are _either_ (a) an FQDN or (b) a list of QTYPEs.  To look up an Indirection RRTYPE, a recursive follows the chain of FQDNs (case a) until it reaches case b.  In case b, the authoritative gathers all the listed QTYPEs for the QNAME and returns them (as Additional) along with the Indirection RR.  The recursive returns all this to the stub.

If the recursive is delinquent, this can (and MUST) all be done by the stub/client.

HTTPSSVC is an Indirection RRTYPE initially intended for use with the A, AAAA, *ESNIKEYS*, and *HTTPSALT* QTYPEs.
- ESNIKEYS is just the ESNIKeys.
- HTTPSALT is the ALPN and port (i.e. `h2=:8002` in a compact encoding)

Rationale: 
- Avoids adding another key-value layer on top of the DNS itself
- Keeps all info for one endpoint in one name (unlike current draft)
- Implementing any future Indirection RRTYPE (NS2?) is a one-line change to DNS code (just handle it identically to HTTPSSVC).
- Can easily drop support for IPv4
- Can easily add new types of info (just define an RRTYPE and add it to your QTYPE list)
- Still fully equivalent to Alt-Svc
- No base64

Problems:
- No binding between multiple ESNIKEYS and HTTPSALT values in a single name.  If h2 and h3 have different ESNIKeys, they have to have different names (as in our draft's example with svc2.example.com and svc3.example.com).
- Zone files could end up with a lot of lines.
- Possible to screw up by listing a QTYPE for a sister record that isn't actually present.  This should probably be a parse error when loading the zone, but is there a precedent for multi-entry consistency checking?
- Every future Alt-Svc key also needs a new RRTYPE to be usable in HTTPSSVC.  (On the plus side, keys that aren't safe for use in DNS are unrepresentable.)
- Not clear how this interacts with DNS64.  (Doesn't seem worse than current draft.)

Open question: Is there a way to extend the [Unknown RRTYPE](https://tools.ietf.org/html/rfc3597) system to support handling an "Unknown Indirection RRTYPE", so further future Indirection RRTYPEs can be handled by future legacy DNS code?

**Comment by enygren** [comment]
I worry that the Indirection RRType doesn't solve enough problems (such as service bindings).  It also seems like yet another attempt at the multi-query style approach of which there have been a huge number of failed drafts.

**Comment by enygren** [comment]
What I'd been thinking of for option 2/3 (although option 1 may just be safer/simpler and good enough):

* Generalize the HTTPSSVC record as something like "B" (or "SRV2") and remove the HTTPS-specific semantics from the doc.  Specify that other documents may create service-specific instantiations with their own RRtypes.  Protocols/services without special needs and willing to use SRV-style attribute leaf labels could also just use "B" directly. 

* In a separate draft define the "HTTPS" RRtype as an instantiation of "B" and define the HTTPS-specific semantics and behaviors, such as the mapping to AltSvc.  (A similar separate draft could also define "NS2".)  Separate RRTypes are really only needed when differentiation between services is needed on a name without attribute leaf labels.
* How to handle the SvcFieldValue key=value pairs is one of the biggest open questions for me:
    * The simple model would be to leave this as plain text and leave it up to application/service protocol bindings to define meanings.  HTTPS could then continue to use the Alt-Svc format.
    * A much more ambitious approach would be to define the key=value pairs in a much structured way (perhaps but with a mapping for HTTPS over to Alt-Svc format in that separate draft).  This could allow for a few types of values (and I'm not sure what the right set of these is):  strings;  binary blobs (eg, for keys);  inlined RRDATA; references over to other {RRNames/RRTypes}.  This could become especially powerful if done right by allowing something like an ESNI key to either be literally included in the SvcFieldValue, or to be the name of another record (with a different TTL) containing the ESNI key, for example.  This could also support inlining AAAA/A records into a SvcFieldValue value element, perhaps.  This pushes even more complexity into clients, perhaps.

**Comment by moonshiner** [comment]
I think we need to make the decision on your approval speed.  Doing something more generic will definitely slow down DNSOP as they debate minutia, and perhaps spending all goodwill.

**Comment by bemasc** [comment]
>   * The simple model would be to leave this as plain text and leave it up to application/service protocol bindings to define meanings.  HTTPS could then continue to use the Alt-Svc format.
>   * A much more ambitious approach would be to define the key=value pairs in a much structured way

As an intermediate option, I propose a binary type-length-value store (16-bit keys and lengths).  Type codes are controlled by a new IANA registry.  Data format is type-dependent.

HTTPSSVC (and NS2, etc.) would share the global IANA type code registry, adding type codes for port, ALPN, and ESNIKeys (which are all we need right now).  Some type codes (like port, ESNIKeys) are likely to be useful in multiple RRTYPEs, while others (like ALPN) are likely to be exclusive to a single RRTYPE.

HTTPSSVC's zone-file representation remains unchanged.  SRV2/B also has a host file representation that doesn't require parsing the TLV data, and HTTPSSVC can be represented in this form if the implementation doesn't recognize one of the keys.

What do you think?

**Comment by enygren** [comment]
I have a first pass at doing a proposed generalization on this branch:

https://github.com/MikeBishop/dns-alt-svc/blob/enygren-svcb-generalization-1/draft-nygren-httpbis-httpssvc.md

It does something roughly equivalent to what @bemasc proposes in the previous comment.  It has a SVCB record (name is a placeholder) that is general with an IANA parameter key registry (with 16-bit key values).  It separates out HTTPS and Alt-Svc into a dedicated section of the document where it specifies HTTPS-specific behaviors as well as the mapping from SVCB RRs to Alt-Svc values.

**Comment by enygren** [comment]
Included in the latest draft draft-nygren-dnsop-svcb-httpssvc which will be published shortly.
