### ISSUE TITLE
Consider removing the in-band Alt-Svc precedence guarantee

### ISSUE THREAD

**Issue by bemasc** [MikeBishop/dns-alt-svc#58]
Currently, in-band Alt-Svc always has precedence over HTTPSSVC, and the presence of a cached Alt-Svc is supposed to disable the HTTPSSVC query altogether.  However, this could be a problem for Chrome.

Chrome currently implements only "local Alt-Svc", i.e. Alt-Svc where the origin hostname is empty.  All other Alt-Svc headers are ignored.

Consider a site hosted in a multi-CDN configuration, using QUIC on both CDNs.  Currently, that site could send a header like `h3=:443`, and Chrome would upgrade to QUIC.

Now suppose that both CDNs support ESNI.  The site could send additional Alt-Svc headers like `h3=cdn1.example:443; esnikeys=ABC...` and `h3=cdn2.example:443; esnikeys=123...`, but Chrome would ignore both of these, so Chrome users would get QUIC but not ESNI.

If some Chrome users can query HTTPSSVC, those users could get the full package for ESNI through the DNS.  However, the presence of `h3=:443` in the Alt-Svc cache would prevent them from even doing the HTTPSSVC query (in the current draft).

A straightforward solution here would be to declare that the precedence of HTTPSSVC vs. Alt-Svc is implementation-defined.  This might reduce the ability of origins to fine-tune suboptimal HTTPSSVC, but it gives clients more flexibility to do what makes sense for them.

**Comment by davidben** [comment]
Another example of the sort of complex interactions between Alt-Svc and HTTPSSVC: HTTPSSVC's http-to-https upgrade does not have an Alt-Svc analog. That means an existing Alt-Svc entry on an http origin would mask off the upgrade behavior and prevent a client from discovering it.

Alt-Svc is mostly an https-only thing, so this mostly doesn't matter, though I believe RFC8164 defines an http use. (Although clients [shouldn't implement](https://www.mozilla.org/en-US/security/advisories/mfsa2015-44/) RFC8164 anyway.)

In general, any property provided by HTTPSSVC but not Alt-Svc becomes a bit of a pickle.

**Comment by MikeBishop** [comment]
@davidben, I think you're incorrect in pointing to that vulnerability as a reason not to implement RFC8164.  Mozilla had a bug, wherein certificate verification could be bypassed.  They fixed it.  That doesn't say anything about the mechanism itself, which continues to require that the certificate be checked.

**Comment by davidben** [comment]
Right, it's possible to implement it correctly. But it's a huge source of complexity risk in a very security-sensitive part of a modern HTTP client, with that Mozilla bug demonstrating that risk. Such a risk needs to be matched by benefit, which I don't believe exists.

Regardless, that's an aside. RFC8164, not the lack of it, is the reason why the alt-svc/httpssvc interactions are a problem.

**Comment by bemasc** [comment]
This precedence rule has been removed, replaced by a "MAY".
