### ISSUE TITLE
Consider switching the SvcDomainName and SvcFieldPriority in presentation format

### ISSUE THREAD

**Issue by bemasc** [MikeBishop/dns-alt-svc#63]
Currently, the format is `[SvcFieldPriority] [SvcDomainName] [SvcFieldValue]`.  I think it should probably be `[SvcDomainName] [SvcFieldPriority] [SvcFieldValue]`.  Then in AliasForm, the redundant `0` priority can be omitted without making the parser more complex.

We could maintain the current wire format, or reverse the order there too.

**Comment by enygren** [comment]
The counter-point and why I chose the current ordering is for consistency with SRV, URI, and MX,
both of which have the priority come before the target domain name.  NAPTR also has order and pref come before other things.  

It seems like it could be a usability issue here to have ordering that is less consistent than the precedent set by most other record types.

**Comment by enygren** [comment]
(Crazy idea could be for SvcFieldPriority to be a weight in AliasForm.  ie, if multiple are present then clients pick between one based on weight?  Not sure if this is worth complexity.)

**Comment by bemasc** [comment]
I don't think there's any risk of users getting it wrong (you'll get a parse error if you put them in backwards), but I take your point that there is a strong tradition here.  I'd like to poll some implementers and come back to this.

**Comment by bemasc** [comment]
WG seems to favor the current format
