### ISSUE TITLE
Clarify behavior when alpn=h2 but origin only supports http/1.1 (and vice-versa)

### ISSUE THREAD

**Issue by enygren** [MikeBishop/dns-alt-svc#79]
We should clarify the behavior for how alpn=h2 and alpn=http/1.1 interact with ALPN negotiation over TLS with an origin, including in cases where only one is specified in the DNS but where only the other can get negotiated via TLA.

One option would be to call this out and recommend that "h2" can negotiate to http/1.1 and/or h2 if only one is specified in HTTPSSVC records.

**Comment by bemasc** [comment]
I could see something like "client MUST include the specified ALPN and SHOULD include any others that it would also support".

> in cases where only one is specified in the DNS but where only the other can get negotiated

Why would this happen?

**Comment by bemasc** [comment]
@MikeBishop What do you think is supposed to happen with ALPN in Alt-Svc?  If the Alt-Svc says "h2=...", can the client also offer "http/1.1" in the ClientHello?  RFC 7838 doesn't seem very clear on this.

**Comment by enygren** [comment]
Synchronization between DNS configuration and HTTP/TLS server configuration seems challenging.  I suspect it is highly likely that mismatches here will happen regularly, especially as the h2 vs http/1.1 variations may be a little more subtle than QUIC.  It would be nice if things here had good usability and just worked as long as behaviors are safe and robust.

**Comment by bemasc** [comment]
OK, I added text for this to #78.

**Comment by MikeBishop** [comment]
As best I recall and without rechecking 7838:  With Alt-Svc, the client can offer anything, but if the connection winds up not having the properties the Alt-Svc entry told it to expect, it's not usable.  We might choose to depart from that, however.

**Comment by bemasc** [comment]
Thanks for the explanation.  Please take a look at #78 for the proposed change.

**Comment by MikeBishop** [comment]
Yes, RFC7838 says:
> If the connection to the alternative service does not negotiate the expected protocol (for example, ALPN fails to negotiate h2, or an Upgrade request to h2c is not accepted), the connection to the alternative service MUST be considered to have failed.

The softer stance of "SHOULD include others with equivalent security" seems reasonable, but we might get some pushback on the divergence.

**Comment by bemasc** [comment]
Merged #78
