### ISSUE TITLE
Clarify fallback behaviour

### ISSUE THREAD

**Issue by c-taylor** [MikeBishop/dns-alt-svc#81]
I believe that either this draft or a revision of rfc7838 should clarify the client behaviour or provide stronger guidance for the scenarios:
- Fallback to origin from alternates
-- Both with and without downgrade considerations
- Multiple same priority alternates
-- After random shuffle do I use one? all?
-- Should client fail to origin or same priority?
- Multiple differing priority alternates
-- Fail down the tree or straight to origin?

 

rfc7838 was not explicit here either, which has (probably) led to the fail-back having low implementation. Defined/predictable client failover behaviour is a big win.

Happy to help with words if you think there's a place for this...

**Comment by bemasc** [comment]
One thing I've learned here is that browser vendors do not like being told how to structure their fallback logic, which it seems is often deeply entangled with other aspects of their codebase and full of hard-won performance and compatibility hacks.  We should be clear in our recommendations about what is mandatory, but I don't think we should be more prescriptive than necessary.

**Comment by bemasc** [comment]
Current text is "If the connection fails, the client MAY try to connect using values from a lower-priority record."

**Comment by enygren** [comment]
@c-taylor : there is a bunch more on this in the draft since November.  Do you think the current text is good enough?  (The current fallback description is a "MAY".)
