### ISSUE TITLE
Clarify server behavior

### ISSUE THREAD

**Issue by bemasc** [MikeBishop/dns-alt-svc#86]
We need a careful implementor review on Section 4, particularly regarding what to put in the Additional section for negative responses (with and without DNSSEC).

I also wonder how this would interact with the CHAIN query.

**Comment by bemasc** [comment]
We also need more thought about what goes in the Answer vs. Additional.  If the authoritative puts more stuff in the Answer, will non-SVCB-aware recursives be more likely to forward that stuff to the client?

**Comment by bemasc** [comment]
@marka63 Would you be able to review Section 4 with an eye toward DNSSEC and negative responses?  I'd like to make sure that the recommendations really make sense.

**Comment by enygren** [comment]
Looks like we're waiting on @marka63 to review Section 4 with an eye toward DNSSEC and negative responses before we can close this.

**Comment by moonshiner** [comment]
I will talk to Benno if someone on the Unbound team can also review this.

**Comment by bemasc** [comment]
Resolved by #199
