### ISSUE TITLE
ESNI is not up-to-date with ESNIConfig => ESNIConfigs change

### ISSUE THREAD

**Issue by davidben** [MikeBishop/dns-alt-svc#88]
We changed the ESNI configuration from a single ESNIConfig to a list of ESNIConfigs in https://github.com/tlswg/draft-ietf-tls-esni/pull/200. HTTPSSVC/SVCB needs to be updated to match.

**Comment by enygren** [comment]
See also #127 which may replace the need for this?

**Comment by MikeBishop** [comment]
This section has been substantially reworked.
