### ISSUE TITLE
WebSockets should use HTTPSSVC

### ISSUE THREAD

**Issue by bemasc** [MikeBishop/dns-alt-svc#90]
Despite having their own scheme (ws://, wss://), WebSockets should actually use HTTPSSVC.  This has a firm basis on the Fetch spec, which says that [each WebSocket has an equivalent http(s) URL](https://fetch.spec.whatwg.org/#websocket-opening-handshake), but it has come up as a point of confusion so I think it deserves a sentence in the draft.

**Comment by tfpauly** [comment]
Should just be a SHOULD

**Comment by enygren** [comment]
Especially now that we have HTTPS and SVCB, clarify that clients with a wss:// URL SHOULD use the equivalent https-scheme HTTPS record lookup
