### ISSUE TITLE
Consider requiring support for SNI

### ISSUE THREAD

**Issue by bemasc** [MikeBishop/dns-alt-svc#92]
Clients that do HTTPSSVC should be modern enough to do SNI.

**Comment by chris-wood** [comment]
@bemasc what is the rationale for this?

**Comment by enygren** [comment]
@chris-wood : Same as with the SNI requirement in Alt-Svc and HTTP/2.  Servers must be able to assume that they will have a way to provide the proper server certificate to a client based on either SNI or the inner-SNI in ECH without needing to have an IP address per service endpoint.
One use-case for HTTPSSVC is to allow the default A/AAAA records to point to a per-certificate-per-cluster virtual IP (limited to a subset of clusters) for legacy client support but where the SvcDomainName points to a name that covers a much broader set of server clusters that support multiplexing via SNI. Almost all clients do support SNI, but we prevent backslide to avoid causing problems with continued growth/scaling of HTTPS adoption.

**Comment by chris-wood** [comment]
What seems strange (to me) is that HTTPSSVC is purely a DNS artifact, and can (in theory) be used without TLS. As a silly example, imagine we used HTTPSSVC to publish public keys used for a protocol that is *not* TLS. Imagine further that the client consuming one of these records only uses this other fictitious protocol, and doesn't implement TLS. Would this prevent said client from using the record? If so, that seems needlessly prohibitive. Perhaps the text should say that clients using HTTPSSVC records for subsequent TLS connections must support SNI, to be more clear?

**Comment by bemasc** [comment]
@chris-wood This requirement only applies to HTTPSSVC, not SVCB, so it's not used for any protocol other than HTTPS, i.e. TLS.  As such, I can't think of a way to encounter the problem you're describing (unless HTTP/4 doesn't use TLS...).

**Comment by chris-wood** [comment]
Got it. That does clarify!
