### ISSUE TITLE
Require sorted order of SvcFieldParams?

### ISSUE THREAD

**Issue by bemasc** [MikeBishop/dns-alt-svc#96]
The order of the SvcFieldParams is not meaningful.  Should we require (and enforce?) that they appear in key order?  This makes serialization more annoying to implement, but also removes a source of entropy that could be used to fingerprint authoritative implementations.

**Comment by moonshiner** [comment]
no.   they should be easy to sort when they arrive, yes?

**Comment by MikeBishop** [comment]
Done.

**Comment by tfpauly** [comment]
Fixed in #109
